/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.origami.testit_allure.test_it.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * FlakyBulkModel
 */
@JsonPropertyOrder({
  FlakyBulkModel.JSON_PROPERTY_AUTOTEST_SELECT,
  FlakyBulkModel.JSON_PROPERTY_VALUE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FlakyBulkModel {
  public static final String JSON_PROPERTY_AUTOTEST_SELECT = "autotestSelect";
  private AutotestSelectModel autotestSelect;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Boolean value;

  public FlakyBulkModel() { 
  }

  public FlakyBulkModel autotestSelect(AutotestSelectModel autotestSelect) {
    this.autotestSelect = autotestSelect;
    return this;
  }

   /**
   * Get autotestSelect
   * @return autotestSelect
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTOTEST_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AutotestSelectModel getAutotestSelect() {
    return autotestSelect;
  }


  @JsonProperty(JSON_PROPERTY_AUTOTEST_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutotestSelect(AutotestSelectModel autotestSelect) {
    this.autotestSelect = autotestSelect;
  }


  public FlakyBulkModel value(Boolean value) {
    this.value = value;
    return this;
  }

   /**
   * Are autotests flaky
   * @return value
  **/
  @jakarta.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Are autotests flaky")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(Boolean value) {
    this.value = value;
  }


  /**
   * Return true if this FlakyBulkModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlakyBulkModel flakyBulkModel = (FlakyBulkModel) o;
    return Objects.equals(this.autotestSelect, flakyBulkModel.autotestSelect) &&
        Objects.equals(this.value, flakyBulkModel.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autotestSelect, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlakyBulkModel {\n");
    sb.append("    autotestSelect: ").append(toIndentedString(autotestSelect)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

