/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.origami.testit_allure.test_it.client.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets TestResultOutcome
 */
public enum TestResultOutcome {
  
  INPROGRESS("InProgress"),
  
  PASSED("Passed"),
  
  FAILED("Failed"),
  
  SKIPPED("Skipped"),
  
  BLOCKED("Blocked");

  private String value;

  TestResultOutcome(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TestResultOutcome fromValue(String value) {
    for (TestResultOutcome b : TestResultOutcome.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

